packages:
  - apps/*
  - docs/*
  - examples/*
  - packages/*

catalog:
  '@algolia/client-search': 5.39.0
  '@antfu/eslint-config': 5.4.1
  '@antfu/ni': 26.1.0
  '@changesets/cli': 2.29.7
  '@codemirror/language': 6.11.3
  '@codemirror/legacy-modes': 6.5.2
  '@codemirror/state': 6.5.2
  '@commitlint/cli': 20.1.0
  '@commitlint/config-conventional': 20.0.0
  '@eslint-react/eslint-plugin': 1.53.1
  '@eslint/eslintrc': 3.3.1
  '@iconify/react': 6.0.2
  '@manypkg/get-packages': 3.1.0
  '@nuxt/icon': 2.0.0
  '@nuxtjs/robots': 5.5.5
  '@ohm-js/cli': 2.0.1
  '@playwright/test': 1.55.1
  '@tailwindcss/postcss': 4.1.14
  '@tanstack/react-query': 5.90.2
  '@tanstack/vue-query': 5.90.2
  '@testing-library/react': 16.3.0
  '@trpc/client': 11.6.0
  '@trpc/next': 11.6.0
  '@trpc/react-query': 11.6.0
  '@trpc/server': 11.6.0
  '@turbo/gen': 2.5.8
  '@types/d3-drag': 3.0.7
  '@types/d3-force': 3.0.10
  '@types/d3-scale': 4.0.9
  '@types/d3-scale-chromatic': 3.1.0
  '@types/d3-selection': 3.0.11
  '@types/d3-zoom': 3.0.8
  '@types/eslint': 9.6.1
  '@types/leaflet': 1.9.20
  '@types/node': 24.6.2
  '@types/react': 19.2.0
  '@types/react-dom': 19.2.0
  '@types/resize-observer-browser': 0.1.11
  '@unhead/vue': 2.0.17
  '@unocss/nuxt': 66.5.2
  '@unocss/reset': 66.5.2
  '@vite-pwa/nuxt': 1.0.4
  '@vitejs/plugin-vue': 6.0.1
  '@vitejs/plugin-vue2': 2.3.4
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  '@vue/component-compiler-utils': 3.3.0
  '@vue/shared': 3.5.22
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 13.9.0
  '@vueuse/nuxt': 13.9.0
  astro-eslint-parser: 1.2.2
  autoprefixer: 10.4.21
  babel-core: 7.0.0-bridge.0
  bundlesize2: 0.0.35
  cac: 6.7.14
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  codemirror: 6.0.2
  critters: 0.0.25
  cross-env: 10.1.0
  csvtojson: 2.0.10
  d3-dag: 1.1.0
  d3-drag: 3.0.0
  d3-force: 3.0.0
  d3-scale: 4.0.2
  d3-scale-chromatic: 3.1.0
  d3-selection: 3.0.0
  d3-zoom: 3.0.0
  eslint: 9.37.0
  eslint-config-next: 15.5.4
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-astro: 1.3.1
  eslint-plugin-format: 1.0.2
  eslint-plugin-import: 2.32.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-markdown: 5.1.0
  eslint-plugin-md: 1.0.19
  eslint-plugin-react-hooks: 6.1.1
  eslint-plugin-react-refresh: 0.4.23
  eslint-plugin-svelte: 3.12.4
  eslint-plugin-tsdoc: 0.4.0
  eslint-plugin-turbo: 2.5.8
  eslint-plugin-yml: 1.19.0
  execa: 9.6.0
  flush-promises: 1.0.2
  husky: 9.1.7
  jsdom: 27.0.0
  jsonc-parser: ^3.3.1
  kolorist: 1.8.0
  leaflet: 1.9.4
  leaflet.markercluster: 1.5.3
  lint-staged: 16.2.3
  localforage: 1.10.0
  lucide-react: 0.544.0
  next: 15.5.4
  next-seo: 6.8.0
  node-fetch: 3.3.2
  node-fetch-native: 1.6.7
  nuqs: ^2.7.1
  nuxt: 4.1.2
  ohm-js: 17.2.1
  open: 10.2.0
  picocolors: 1.1.1
  postcss: 8.5.6
  publint: 0.3.13
  react: 19.2.0
  react-dom: 19.2.0
  react-leaflet: 5.0.0
  react-leaflet-markercluster: 5.0.0-rc.0
  react-query: 3.39.3
  react-viewport-list: 7.1.2
  reactflow: 11.11.4
  rimraf: 6.0.1
  splitpanes: 4.0.4
  superjson: 2.2.2
  syncpack: 13.0.4
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.14
  taze: 19.7.0
  tsx: 4.20.6
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  ufo: 1.6.1
  unbuild: 3.6.1
  unplugin-vue-components: 29.1.0
  use-debounce: 10.0.6
  use-local-storage: 3.0.0
  vercel: 48.2.0
  vite: 7.1.9
  vite-plugin-dts: 4.5.4
  vite-ssg: 28.1.0
  vitepress: 1.6.4
  vitest: 3.2.4
  vue: 3.5.22
  vue-codemirror: 6.1.1
  vue-router: 4.5.1
  vue-template-compiler: 2.7.16
  vue-toastification: 2.0.0-rc.5
  vue-tsc: 3.1.0
  yaml: 2.8.1
  yaml-eslint-parser: 1.3.0
  zod: 4.1.11

catalogMode: strict

catalogs:
  vue2:
    '@vue/test-utils': 1.3.6
    vue: 2.7.16
