packages:
  - apps/*
  - docs/*
  - examples/*
  - packages/*

catalog:
  '@algolia/client-search': 5.48.0
  '@antfu/ni': 28.2.0
  '@changesets/cli': 2.29.8
  '@codemirror/language': 6.12.1
  '@codemirror/legacy-modes': 6.5.2
  '@commitlint/cli': 20.4.1
  '@commitlint/config-conventional': 20.4.1
  '@iconify/react': 6.0.2
  '@manypkg/get-packages': 3.1.0
  '@nuxt/icon': 2.2.1
  '@nuxtjs/robots': 5.7.0
  '@ohm-js/cli': 2.0.1
  '@playwright/test': 1.58.1
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.20
  '@tanstack/vue-query': 5.92.9
  '@testing-library/react': 16.3.2
  '@trpc/client': 11.9.0
  '@trpc/next': 11.9.0
  '@trpc/react-query': 11.9.0
  '@trpc/server': 11.9.0
  '@types/d3-drag': 3.0.7
  '@types/d3-force': 3.0.10
  '@types/d3-scale': 4.0.9
  '@types/d3-scale-chromatic': 3.1.0
  '@types/d3-selection': 3.0.11
  '@types/d3-zoom': 3.0.8
  '@types/leaflet': 1.9.21
  '@types/node': 24.10.11
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@types/resize-observer-browser': 0.1.11
  '@unhead/vue': 2.1.2
  '@unocss/nuxt': 66.6.0
  '@unocss/reset': 66.6.0
  '@vite-pwa/nuxt': 1.1.0
  '@vitejs/plugin-vue': 6.0.4
  '@vitejs/plugin-vue2': 2.3.4
  '@vitest/browser-playwright': 4.0.18
  '@vitest/coverage-v8': 4.0.18
  '@vitest/ui': 4.0.18
  '@vue/shared': 3.5.27
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 14.2.0
  '@vueuse/nuxt': 14.2.0
  autoprefixer: 10.4.24
  cac: 6.7.14
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  codemirror: 6.0.2
  critters: 0.0.25
  cross-env: 10.1.0
  csvtojson: 2.0.14
  d3-dag: 1.1.0
  d3-drag: 3.0.0
  d3-force: 3.0.0
  d3-scale: 4.0.2
  d3-selection: 3.0.0
  d3-zoom: 3.0.0
  execa: 9.6.1
  flush-promises: 1.0.2
  husky: 9.1.7
  jsdom: 27.4.0
  jsonc-parser: 3.3.1
  kolorist: 1.8.0
  leaflet: 1.9.4
  leaflet.markercluster: 1.5.3
  lint-staged: 16.2.7
  localforage: 1.10.0
  lucide-react: 0.563.0
  next: 16.1.6
  next-seo: 7.1.0
  node-fetch: 3.3.2
  node-fetch-native: 1.6.7
  nuqs: 2.8.8
  nuxt: 4.3.0
  ohm-js: 17.3.0
  open: 11.0.0
  oxfmt: 0.28.0
  oxlint: 1.43.0
  oxlint-tsgolint: 0.11.4
  picocolors: 1.1.1
  postcss: 8.5.6
  publint: 0.3.17
  react: 19.2.4
  react-dom: 19.2.4
  react-leaflet: 5.0.0
  react-leaflet-markercluster: 5.0.0-rc.0
  react-viewport-list: 7.1.2
  reactflow: 11.11.4
  serve: 14.2.5
  splitpanes: 4.0.4
  superjson: 2.2.6
  syncpack: 13.0.4
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  taze: 19.9.2
  tsdown: 0.20.3
  tsx: 4.21.0
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  ufo: 1.6.3
  use-debounce: 10.1.0
  use-local-storage: 3.0.0
  vite: 7.3.1
  vite-plugin-dts: 4.5.4
  vite-ssg: 28.3.0
  vitepress: 1.6.4
  vitest: 4.0.18
  vue: 3.5.27
  vue-codemirror: 6.1.1
  vue-router: 4.6.4
  vue-template-compiler: 2.7.16
  vue-toastification: 2.0.0-rc.5
  vue-tsc: 3.2.4
  yaml: 2.8.2
  zod: 4.3.6

catalogMode: strict

catalogs:
  vue2:
    '@vue/test-utils': 1.3.6
    vue: 2.7.16

cleanupUnusedCatalogs: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

packageExtensions:
  vue-template-compiler:
    peerDependencies:
      vue: 2.7.16

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2 || 6.3.1
  - vite@5.4.21
