export default defineAppConfig({
  ui: {
    colors: {
      primary: 'red',
    },
    icons: {
      arrowDown: 'hugeicons:arrow-down-02',
      arrowLeft: 'hugeicons:arrow-left-02',
      arrowRight: 'hugeicons:arrow-right-02',
      arrowUp: 'hugeicons:arrow-up-02',
      caution: 'hugeicons:alert-circle',
      check: 'hugeicons:tick-01',
      chevronDoubleLeft: 'hugeicons:arrow-left-double',
      chevronDoubleRight: 'hugeicons:arrow-right-double',
      chevronDown: 'hugeicons:arrow-down-01',
      chevronLeft: 'hugeicons:arrow-left-01',
      chevronRight: 'hugeicons:arrow-right-01',
      chevronUp: 'hugeicons:arrow-up-01',
      close: 'hugeicons:cancel-01',
      copy: 'hugeicons:copy-01',
      copyCheck: 'hugeicons:copy-02',
      dark: 'hugeicons:moon-02',
      drag: 'hugeicons:drag-drop',
      ellipsis: 'hugeicons:dashed-line-01',
      error: 'hugeicons:cancel-circle',
      external: 'hugeicons:arrow-up-right-01',
      eye: 'hugeicons:view',
      eyeOff: 'hugeicons:view-off-slash',
      file: 'hugeicons:file-empty-02',
      folder: 'hugeicons:folder-01',
      folderOpen: 'hugeicons:folder-02',
      hash: 'hugeicons:link-01',
      info: 'hugeicons:information-square',
      light: 'hugeicons:sun-03',
      loading: 'hugeicons:loading-02',
      menu: 'hugeicons:menu-01',
      minus: 'hugeicons:minus-sign',
      panelClose: 'hugeicons:sidebar-left-01',
      panelOpen: 'hugeicons:sidebar-right-01',
      plus: 'hugeicons:plus-sign',
      reload: 'hugeicons:reload',
      search: 'hugeicons:search-01',
      stop: 'hugeicons:stop',
      success: 'hugeicons:checkmark-circle-01',
      system: 'hugeicons:computer',
      tip: 'hugeicons:bulb',
      upload: 'hugeicons:upload-01',
      warning: 'hugeicons:alert-02',
    },
  },
})
