/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./components/Demo.vue')['default']
    GraphView: typeof import('./components/GraphView.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Status: typeof import('./components/Status.vue')['default']
    UsedIn: typeof import('./components/UsedIn.vue')['default']
  }
}
