<script setup lang="ts">
const accessibleDescription = `Image of two abstract machines with white bodies and golden decorations, generated by Midjourney and licensed under CC BY-NC 4.0.`
</script>

<template>
  <figure
    v-once
    class="relative w-128 lg:w-192 max-w-full children:select-none"
  >
    <img
      src="/hero-first.webp"
      :alt="accessibleDescription"
      class="drop-shadow-custom"
    />
    <img
      src="/hero-second.webp"
      :alt="accessibleDescription"
      class="drop-shadow-custom absolute left-25% top-25%"
    />
    <figcaption class="invisible">{{ accessibleDescription }}</figcaption>
  </figure>
</template>
