<script setup lang="ts">
const accessibleDescription = `Image of two abstract machines with white bodies and golden decorations, generated by Midjourney`
</script>

<template>
  <figure v-once class="relative w-128 lg:w-192 max-w-full">
    <img src="/hero-first.webp" :alt="accessibleDescription" />
    <img
      src="/hero-second.webp"
      :alt="accessibleDescription"
      class="absolute left-25% top-25%"
    />
    <figcaption class="invisible">{{ accessibleDescription }}</figcaption>
  </figure>
</template>

<style scoped>
img {
  filter: drop-shadow(5px 5px 5px rgba(0, 0, 50, 0.35));
}
</style>
