const accessibleDescription = `Image of two abstract machines with white bodies and golden decorations, generated by Midjourney and licensed under CC BY-NC 4.0.`

export function useLogo() {
  return {
    accessibleDescription,
  }
}
